apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - service-preview.yaml
  - rollout.yaml
patches:
  - path: deployment-delete.yaml
images:
  - name: app
    newName: 168852252849.dkr.ecr.us-east-2.amazonaws.com/bizcloud-backend
    newTag: v2
