apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
- ingress-class.yaml
patches:
- path: service-clusterip-patch.yaml
images:
- name: bizcloud-ai
  newName: 168852252849.dkr.ecr.us-east-2.amazonaws.com/bizcloud-ai
  newTag: 6425754c6e2157e1f1d320875ba7c2bcc5502b54
