apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
  - ingress-class.yaml
  - service-preview.yaml
  - rollout.yaml
patches:
  - path: service-clusterip-patch.yaml
  - path: deployment-delete.yaml
images:
  - name: bizcloud-ai
    newName: 168852252849.dkr.ecr.us-east-2.amazonaws.com/bizcloud-ai
    newTag: v2
