apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: app
          env:
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=bizcloud-backend,deployment.environment=prod,k8s.cluster.name=jim-testing,k8s.namespace.name=$(NAMESPACE),k8s.deployment.name=bizcloud-backend,k8s.pod.name=$(POD_NAME),k8s.node.name=$(NODE_NAME)
            - name: OTEL_SERVICE_NAME
              value: bizcloud-backend
            - name: DEPLOYMENT_NAME
              value: bizcloud-backend
