- op: replace
  path: /metadata/name
  value: bizcloud-frontend
- op: replace
  path: /spec/selector/matchLabels/app
  value: bizcloud-frontend
- op: replace
  path: /spec/template/metadata/labels/app
  value: bizcloud-frontend
- op: replace
  path: /spec/template/spec/containers/0/name
  value: bizcloud-frontend
- op: replace
  path: /spec/template/spec/containers/0/env/0/value
  value: service.name=bizcloud-frontend,deployment.environment=prod,k8s.cluster.name=jim-testing,k8s.namespace.name=$(NAMESPACE),k8s.deployment.name=bizcloud-frontend,k8s.pod.name=$(POD_NAME),k8s.node.name=$(NODE_NAME)
- op: replace
  path: /spec/template/spec/containers/0/env/1/value
  value: bizcloud-frontend
- op: replace
  path: /spec/template/spec/containers/0/env/11/value
  value: bizcloud-frontend
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: BACKEND_BASE_URL
    value: http://bizcloud-backend
