- op: replace
  path: /metadata/name
  value: bizcloud-frontend
- op: replace
  path: /spec/selector/matchLabels/app
  value: bizcloud-frontend
- op: replace
  path: /spec/template/metadata/labels/app
  value: bizcloud-frontend
- op: replace
  path: /spec/template/spec/containers/0/name
  value: bizcloud-frontend
