apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../../_shared/overlays/eks-alb-blue-green
  - service-preview.yaml
  - rollout.yaml
  - ingress.yaml
patches:
  - path: service-clusterip-patch.yaml
  - path: deployment-delete.yaml
images:
  - name: bizcloud-frontend
    newName: 168852252849.dkr.ecr.us-east-2.amazonaws.com/bizcloud-frontend
    newTag: v2
